# Generated by Django 3.0.8 on 2020-12-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='网站名称')),
                ('link', models.URLField(verbose_name='网站链接')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击数')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常用链接',
                'verbose_name_plural': '常用链接',
                'ordering': ['-clicks'],
            },
        ),
    ]
